# Generated by Django 2.0.2 on 2018-04-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
